Repository t-norm/type-Plus-Plus, pull requests merged in 2022-02, with the labels that each got.

#5 Feature/dashboard
  client/public/index.html
  client/src/App.js
  client/src/components/Dashboard/Achievements.js
  client/src/components/Dashboard/Dashboard.js
  client/src/components/Dashboard/ProfilePic.js
  client/src/components/Dashboard/Progess.js
  client/src/components/Dashboard/UserInfo.js
  client/src/components/Dashboard/index.js
  package-lock.json
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/server.js
Labels: enhancement

#8 Feature/game
  client/package.json
  client/src/App.js
  client/src/components/Game/Game.jsx
  client/src/pages/Home.js
Labels: enhancement

#10 Dashboard features
  client/src/assets/images/no-profile-picture.svg
  client/src/components/Header/Header.jsx
  client/src/components/Login/Login.jsx
  client/src/components/Signup/Signup.jsx
  client/src/components/UserInfo/UserInfo.jsx
  client/src/pages/Dashboard.js
  client/src/utils/queries.js
  server/models/Scores.js
  server/models/User.js
  server/models/index.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#11 Feature/bio
  client/src/components/UserInfo/UserInfo.jsx
  client/src/utils/mutations.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#12 Feature/game
  client/src/App.js
  client/src/components/Game/Game.jsx
  client/src/pages/Home.js
  server/controllers/api/index.js
  server/controllers/index.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: enhancement

#13 Fixed a few small bugs from last push
  client/src/pages/Home.js
  server/controllers/api/index.js
  server/package-lock.json
  server/package.json
Labels: bug

#18 Feature/game
  client/src/App.js
  client/src/components/Game/Game.jsx
  client/src/components/Login/Login.jsx
  client/src/pages/Home.js
  client/src/utils/mutations.js
  server/controllers/api/index.js
  server/models/Scores.js
  server/schemas/typeDefs.js
Labels: enhancement

#19 Feature/chart
  client/package-lock.json
  client/package.json
  client/src/components/Chart/Chart.jsx
  client/src/components/Chart/index.js
  client/src/pages/Home.js
  client/src/utils/API.js
  client/src/utils/helpers.js
  client/src/utils/localStorage.js
  client/src/utils/queries.js
Labels: enhancement

#21 Feature/body styling
  client/package-lock.json
  client/package.json
  client/src/components/Chart/Chart.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Login/Login.jsx
  client/src/components/Signup/Signup.jsx
  client/src/index.js
  client/src/pages/Dashboard.js
  client/src/pages/Home.js
  client/src/utils/helpers.js
  client/src/utils/queries.js
  client/tailwind.config.js
  server/schemas/typeDefs.js
  server/server.js
Labels: enhancement

#23 Rounding numbers and focusing text area
  client/src/components/Game/Game.jsx
  client/src/pages/Home.js
Labels: enhancement

#25 Feature/profile
  client/src/App.js
  client/src/components/Achievements/index.js
  client/src/components/Chart/Chart.jsx
  client/src/components/DashboardAchievements/DashboardAchievements.jsx
  client/src/components/DashboardAchievements/index.js
  client/src/components/DashboardProgress/DashboardProgress.jsx
  client/src/components/DashboardProgress/index.js
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/components/DashboardUserInfo/index.js
  client/src/components/ProfileAchievements/ProfileAchievements.jsx
  client/src/components/ProfileAchievements/index.js
  client/src/components/ProfileProgress/ProfileProgress.jsx
  client/src/components/ProfileProgress/index.js
  client/src/components/ProfileUserInfo/ProfileUserInfo.jsx
  client/src/components/ProfileUserInfo/index.js
  client/src/components/Progress/index.js
  client/src/components/UserInfo/index.js
  client/src/pages/Dashboard.js
  client/src/pages/Profile.js
  client/src/utils/queries.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#26 Feature/location
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/components/EditModal/EditModal.jsx
  client/src/components/ProfileUserInfo/ProfileUserInfo.jsx
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/models/User.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#27 Feature/leaderboard
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/ActivityLeaderBoard/index.js
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/GlobalLeaderBoard/index.js
  client/src/pages/Home.js
  client/src/pages/LeaderBoard.js
  client/src/utils/queries.js
  server/models/User.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#28 Feature/game
  client/src/components/Game/Game.jsx
Labels: enhancement

#29 Feature/leaderboard
  client/package-lock.json
  client/package.json
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/pages/Home.js
Labels: enhancement

#32 Feature/achievement badges
  server/models/Badge.js
  server/models/User.js
  server/models/index.js
  server/package.json
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/seeders/seeds.js
Labels: enhancement

#33 Improvements
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/Header/Header.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
  client/src/pages/Home.js
  server/schemas/typeDefs.js
Labels: enhancement

#34 Add friends
  client/src/App.js
  client/src/components/ProfileUserInfo/ProfileUserInfo.jsx
  client/src/pages/Profile.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#37 Improvements
  client/src/assets/badges/accuracy-badge-1.png
  client/src/assets/badges/accuracy-badge-2.png
  client/src/assets/badges/accuracy-badge-3.png
  client/src/assets/badges/age-badge-1.png
  client/src/assets/badges/age-badge-2.png
  client/src/assets/badges/age-badge-3.png
  client/src/assets/badges/age-badge-4.png
  client/src/assets/badges/age-badge-5.png
  client/src/assets/badges/crown.png
  client/src/assets/badges/friends-badge-1.png
  client/src/assets/badges/friends-badge-2.png
  client/src/assets/badges/friends-badge-3.png
  client/src/assets/badges/friends-badge-4.png
  client/src/assets/badges/friends-badge-5.png
  client/src/assets/badges/games-badge-1.png
  client/src/assets/badges/games-badge-2.png
  client/src/assets/badges/games-badge-3.png
  client/src/assets/badges/games-badge-4.png
  client/src/assets/badges/games-badge-5.png
  client/src/assets/badges/icons8-certificate-50-2.png
  client/src/assets/badges/icons8-certificate-50.png
  client/src/assets/badges/icons8-certificate.png
  client/src/assets/badges/icons8-cup-50-10.png
  client/src/assets/badges/icons8-cup-50-12.png
  client/src/assets/badges/icons8-cup-50-13.png
  client/src/assets/badges/icons8-cup-50-16.png
  client/src/assets/badges/icons8-cup-50-6.png
  client/src/assets/badges/icons8-cup-50-8.png
  client/src/assets/badges/icons8-flag-50-2.png
  client/src/assets/badges/icons8-medal-50-15.png
  client/src/assets/badges/icons8-medal-50-2.png
  client/src/assets/badges/icons8-medal-50-3.png
  client/src/assets/badges/icons8-medal-50-8.png
  client/src/assets/badges/icons8-medal-50-9.png
  client/src/assets/badges/icons8-medal-50.png
  client/src/assets/badges/icons8-oscar-50.png
  client/src/assets/badges/score-badge-1.png
  client/src/assets/badges/score-badge-2.png
  client/src/assets/badges/score-badge-3.png
  client/src/assets/badges/score-badge-4.png
  client/src/assets/badges/score-badge-5.png
  client/src/assets/badges/streak-badge-1.png
  client/src/assets/badges/streak-badge-2.png
  client/src/assets/badges/streak-badge-3.png
  client/src/assets/badges/streak-badge-4.png
  client/src/assets/badges/streak-badge-5.png
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
Labels: enhancement

#41 Feature/short badge list
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/BadgeList/BadgeList.jsx
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/components/RecentBadge/RecentBadge.jsx
  client/src/components/RecentBadge/index.js
  client/src/pages/Home.js
  client/src/utils/queries.js
  server/models/Badge.js
  server/models/User.js
  server/public/images/wizard_nobg.png
  server/schemas/typeDefs.js
  server/seeders/seeds.js
Labels: enhancement

#42 Deploy v1
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/BadgeList/BadgeList.jsx
  client/src/components/Game/Game.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/RecentBadge/RecentBadge.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
  client/src/pages/Badges.js
  client/src/pages/Dashboard.js
  client/src/pages/Home.js
  client/src/utils/queries.js
  server/models/User.js
  server/schemas/typeDefs.js
  server/server.js
Labels: enhancement

#44 Profile picture
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/components/EditModal/EditModal.jsx
  client/src/components/Uploader/Uploader.jsx
  client/src/pages/Dashboard.js
  client/src/utils/queries.js
  server/public/images/tumblr_n309teA92U1rpwm80o1_250.jpg
  server/public/images/wizard_nobg.png
  server/schemas/resolvers.js
Labels: enhancement

#45 Layouts
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/components/RecentBadge/RecentBadge.jsx
  client/src/pages/Dashboard.js
Labels: enhancement

#48 Profile page
  client/src/components/Login/Login.jsx
  client/src/components/ProfileUserInfo/ProfileUserInfo.jsx
  client/src/pages/Dashboard.js
  client/src/pages/Profile.js
  client/src/utils/queries.js
Labels: enhancement

#49 Feature/badges
  client/package-lock.json
  client/package.json
  client/src/components/BadgeList/BadgeList.jsx
  client/src/components/DashboardAchievements/DashboardAchievements.jsx
  client/src/components/DashboardAchievements/index.js
  client/src/components/DashboardProgress/DashboardProgress.jsx
  client/src/components/DashboardProgress/index.js
  client/src/components/Friends/Friends.jsx
  client/src/components/Game/Game.jsx
  client/src/components/Login/Login.jsx
  client/src/components/ProfileAchievements/ProfileAchievements.jsx
  client/src/components/ProfileAchievements/index.js
  client/src/components/ProfileProgress/ProfileProgress.jsx
  client/src/components/ProfileProgress/index.js
  client/src/components/RecentBadge/RecentBadge.jsx
  client/src/components/Signup/Signup.jsx
  client/src/pages/Dashboard.js
  client/src/pages/Home.js
  client/src/pages/Profile.js
  client/src/utils/auth.js
  client/src/utils/helpers.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/models/Badge.js
  server/models/User.js
  server/public/images/MAX.jpg
  server/public/images/bode4.jpg
  server/public/images/super_mario_bros_super_show.0.jpg
  server/public/images/tenor.gif
  server/public/images/ws.jpg
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/seeders/seeds.js
Labels: enhancement

#50 Rerender
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/BadgeList/BadgeList.jsx
  client/src/components/Chart/Chart.jsx
  client/src/components/Game/Game.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/RecentBadge/RecentBadge.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
  client/src/pages/Home.js
  client/src/utils/auth.js
  server/server.js
Labels: bug

#51 Refetch bug test
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/BadgeList/BadgeList.jsx
  client/src/components/Chart/Chart.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/RecentBadge/RecentBadge.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
  client/src/pages/Badges.js
  client/src/pages/Home.js
Labels: bug

#52 Xp
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/pages/Dashboard.js
  client/src/utils/helpers.js
Labels: enhancement

#53 Highscore
  client/src/components/Highscore/Highscore.jsx
  client/src/components/Highscore/index.js
  client/src/pages/Home.js
Labels: enhancement

#54 Feature/login signup
  client/public/assets/level-icons/level-1.png
  client/public/assets/level-icons/level-10.png
  client/public/assets/level-icons/level-2.png
  client/public/assets/level-icons/level-3.png
  client/public/assets/level-icons/level-4.png
  client/public/assets/level-icons/level-5.png
  client/public/assets/level-icons/level-6.png
  client/public/assets/level-icons/level-7.png
  client/public/assets/level-icons/level-8.png
  client/public/assets/level-icons/level-9.png
  client/src/App.js
  client/src/components/ForgotPassword/ForgotPassword.jsx
  client/src/components/ForgotPassword/index.js
  client/src/components/Login/Login.jsx
  client/src/components/Login/index.js
  client/src/components/Signup/Signup.jsx
Labels: enhancement

#55 Improvement/leaderboard
  client/package-lock.json
  client/package.json
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/Highscore/Highscore.jsx
  client/src/components/Signup/Signup.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
  client/src/index.css
  client/src/pages/Home.js
  client/src/pages/LeaderBoard.js
Labels: enhancement

#56 XP
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/pages/Home.js
  client/src/utils/helpers.js
Labels: enhancement

#57 Profile xp
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/components/ProfileUserInfo/ProfileUserInfo.jsx
  client/src/utils/queries.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#58 Feature/styling - Dårk möde
  client/package-lock.json
  client/package.json
  client/public/assets/images/logo-dark.svg
  client/public/assets/images/logo.svg
  client/public/favicon.ico
  client/public/index.html
  client/src/App.js
  client/src/components/Footer/Footer.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/Header/Header.jsx
  client/src/index.css
  client/src/index.js
  client/src/pages/Badges.js
  client/src/pages/Dashboard.js
  client/src/pages/Home.js
  client/src/utils/helpers.js
  client/tailwind.config.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: enhancement

#59 Feature/styling
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Login/Login.jsx
  client/src/components/Signup/Signup.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
  client/src/pages/LeaderBoard.js
Labels: enhancement

#62 Feature/upcoming badge
  LICENSE
  README.md
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/BadgeList/BadgeList.jsx
  client/src/components/Game/Game.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/Highscore/Highscore.jsx
  client/src/components/UpcomingBadge/UpcomingBadge.jsx
  client/src/components/UpcomingBadge/index.js
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
  client/src/pages/Home.js
  server/public/images/bode4.jpg
Labels: enhancement

#64 Pwa
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/public/svcWorker.js
  client/src/index.js
  client/src/reportWebVitals.js
  client/src/service-worker.js
  client/src/serviceWorkerRegistration.js
Labels: enhancement

#67 Bugfix
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/pages/Profile.js
  server/schemas/resolvers.js
Labels: bug

#68 Bugs
  client/src/App.js
  client/src/components/Chart/Chart.jsx
  client/src/components/ForgotPassword/EmailInput.jsx
  client/src/components/Game/Game.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/Highscore/Highscore.jsx
  client/src/components/SecurityQuestion/SecurityQuestion.jsx
  client/src/components/UpcomingBadge/UpcomingBadge.jsx
  client/src/pages/Home.js
Labels: bug

#69 Pwa
  client/public/logo120.png
  client/public/logo128.png
  client/public/logo144.png
  client/public/logo152.png
  client/public/logo180.png
  client/public/logo384.png
  client/public/logo72.png
  client/public/logo96.png
  client/public/manifest.json
  client/public/svcWorker.js
Labels: enhancement

#71 Feature/leaderboard tabs
  client/src/components/Chart/Chart.jsx
  client/src/components/Login/Login.jsx
  client/src/pages/LeaderBoard.js
Labels: enhancement

#72 Small styling change
  client/src/components/Signup/Signup.jsx
  client/src/pages/LeaderBoard.js
Labels: enhancement

#74 Stuffs
  client/src/App.js
  client/src/components/Header/Header.jsx
Labels: enhancement

#76 Feature/delete user
  client/src/components/ForgotPassword/EmailInput.jsx
  client/src/pages/Dashboard.js
  client/src/utils/mutations.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#77 Bugs
  client/public/index.html
  client/public/svcWorker.js
  client/src/App.js
  client/src/components/Chart/Chart.jsx
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/components/ForgotPassword/EmailInput.jsx
  client/src/components/Login/Login.jsx
  client/src/components/Signup/Signup.jsx
  client/src/components/UpcomingBadge/UpcomingBadge.jsx
  client/src/pages/ForgotPassword.js
  client/src/pages/Profile.js
Labels: bug, enhancement

#78 Feature/mobile responsive
  client/src/components/Footer/Footer.jsx
  client/src/components/Game/Game.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/Header/Header.jsx
  client/src/index.css
  client/src/pages/Home.js
  client/src/utils/helpers.js
Labels: enhancement

#79 Feature/mobile responsive
  client/src/components/Game/Game.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
  client/src/pages/Home.js
  client/src/pages/LeaderBoard.js
Labels: enhancement

#80 Bugs
  client/src/App.js
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/Friends/Friends.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Uploader/Uploader.jsx
  client/src/pages/Badges.js
  client/src/pages/Dashboard.js
  client/src/pages/Profile.js
  client/src/utils/queries.js
  server/schemas/typeDefs.js
Labels: bug, enhancement

#81 Style/badge list
  client/src/components/BadgeList/BadgeList.jsx
  client/src/components/UpcomingBadge/UpcomingBadge.jsx
  client/src/pages/Badges.js
  client/src/pages/Dashboard.js
Labels: enhancement

#83 Feature/loading animation
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/BadgeList/BadgeList.jsx
  client/src/components/Chart/Chart.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/Highscore/Highscore.jsx
  client/src/components/RecentBadge/RecentBadge.jsx
  client/src/components/UpcomingBadge/UpcomingBadge.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
  client/src/pages/Dashboard.js
  client/src/pages/Home.js
Labels: enhancement

#84 Restyled leaderboards for dark mode
  README.md
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
  client/src/pages/Profile.js
Labels: enhancement

#85 Bugs
  client/src/App.js
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/BadgeList/BadgeList.jsx
  client/src/components/Chart/Chart.jsx
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/Highscore/Highscore.jsx
  client/src/components/Login/Login.jsx
  client/src/components/RecentBadge/RecentBadge.jsx
  client/src/components/UpcomingBadge/UpcomingBadge.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
  client/src/pages/Dashboard.js
  client/src/pages/LeaderBoard.js
  client/src/pages/NotFound.js
  client/src/pages/Profile.js
Labels: bug, enhancement

#89 Refactor
  client/src/components/BadgeList/BadgeList.jsx
  client/src/components/Game/Game.jsx
  client/src/components/Highscore/Highscore.jsx
  client/src/utils/helpers.js
Labels: bug, enhancement

#92 Newbranch
  client/public/index.html
  client/src/App.js
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/components/SecurityQuestion/SecurityQuestion.jsx
  client/src/components/Signup/Signup.jsx
  client/src/pages/Dashboard.js
  server/public/images/bode4.jpg
  server/seeders/seeds.js
Labels: bug, enhancement

#93 Bugs
  server/public/images/wizard_nobg.png
  server/server.js
Labels: bug

#94 Fixed bugs in leaderboard components
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
Labels: bug

#95 Bugs
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
  client/src/index.css
Labels: enhancement

#96 Fixed leaderboard pagination for real this time
  client/src/components/ActivityLeaderBoard/ActivityLeaderBoard.jsx
  client/src/components/GlobalLeaderBoard/GlobalLeaderBoard.jsx
  client/src/components/WeeklyLeaderBoard/WeeklyLeaderBoard.jsx
Labels: bug

#99 Refactor
  client/src/components/BadgeList/BadgeList.jsx
  client/src/components/DashboardUserInfo/DashboardUserInfo.jsx
  client/src/pages/LeaderBoard.js
  server/schemas/resolvers.js
Labels: bug, enhancement
